# generate_scripts

. ./lib/read_ini.sh
read_ini $ini_file

function generate_schema(){
    local section=$1
    local name="INI__${section}__name"
    local type="INI__${section}__type"
    local default="INI__${section}__default"
    echo "    ${!name} ${!type} DEFAULT '${!default}'," >> SCHEMA.sql
}

function generate_inputs() {
    local section=$1
    local name="INI__${section}__name"
    local prompt="INI__${section}__prompt"

    echo "
read -p \"${!prompt} [\$${!name}_input]: \" ${!name}" >> lib/input.sh 
    echo "if [[ -z \"\$${!name}\" ]]  && [[ ! -z \"\$${!name}_input\" ]]" >> lib/input.sh
    echo "then
    ${!name}=\$${!name}_input
fi" >> lib/input.sh
    echo "
sqlite3 \$_arg_database \"insert into habits (date, ${!name}) values ('\$_arg_update', '\$${!name}') on conflict(date) do update set ${!name}='\$${!name}';\"" >> lib/input.sh
}


function generate_today() {
    local section=$1
    local name="INI__${section}__name"
    today_row=$2 
    echo "${!name}_input=\$(awk -F '|' '{print \$$today_row}'<<< \"\$current\")" >> lib/today.sh
}

echo "Clearing existing files..."
rm SCHEMA.sql   # Clears the existing SCHEMA.sql
rm lib/input.sh # Clears the existing run scripts
rm lib/today.sh # Clears the existing today.sh script

echo "Generating SCHEMA.sql..."
echo "-- Autogenerated SCHEMA.sql

CREATE TABLE IF NOT EXISTS habits (
    date    DATE DEFAULT ( date('now','locatime') ) UNIQUE," >> SCHEMA.sql

# Generate today.sh
echo "# Check today's recordings and see if there's anything there... if so, grab them...

echo \"Please input habits for: \$_arg_update\"

current=\$( sqlite3 \$_arg_database \"select * from habits WHERE date='\$_arg_update';\" )" >> lib/today.sh

declare -i today_row
today_row=2
for section in ${INI__ALL_SECTIONS}; do
    generate_schema $section
    generate_inputs $section
    generate_today $section $today_row
    today_row=$today_row+1
done

echo -e "    notes TEXT\n);" >> SCHEMA.sql

echo "Generating input.sh..."
echo -e "Generating today.sh...\n"

echo "All set! Have fun tracking!"

exit 0